# This workflow will generate docs for alpa.

name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [ main ]

jobs:
  build_docs:
    runs-on: [self-hosted, alpa]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Build and install api dependencies
        run: |
          pip install matplotlib

      - name: Install sphinx
        run: |
          pip install sphinx sphinx-rtd-theme sphinx-gallery

      - name: Build docs
        run: |
          export ALPA_TUTORIAL_EXEC_PATTERN=none
          cd docs && make html

#      - name: Deploy
#        uses: peaceiris/actions-gh-pages@v3
#        with:
#          personal_token: ${{ secrets.PERSONAL_TOKEN }}
#          external_repository: alpa-projects/alpa-projects.github.io
#          publish_branch: master
#          publish_dir: ./docs/_build/html