name: Release Alpa

on:
  release:
    types: [created]
  workflow_dispatch:

env:
  TWINE_USERNAME: "__token__"
  TWINE_PASSWORD: ${{ secrets.TEST_PYPI_TOKEN }}

jobs:

  build-image:
    runs-on: [self-hosted]

    steps:
      - uses: actions/checkout@v3

      - name: clean up images
        run: |
          docker image prune -f

      - name: build docker image
        run: |
          docker build -t build-alpa-image -f docker/build_alpa.Dockerfile docker/

  release-alpa:
    runs-on: [self-hosted]
    needs: [build-image]

    strategy:
      matrix:
        python: ["3.7", "3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3

      - name: Build Alpa wheels
        run: |
          mkdir -p dist
          docker run --gpus all --tmpfs /build:exec \
          --rm -v $(pwd)/dist:/dist --entrypoint /build_alpa.sh \
          build-alpa-image ${PYTHON_VERSION} ${ALPA_BRANCH}
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          ALPA_BRANCH: ${{ github.ref }}

      - name: Publish to Pypi
        run: |
          echo "Move to self-hosted pypi"
          ls -ltr dist/
          twine upload --repository testpypi dist/*

  update-version:
    runs-on: [ubuntu-latest]
    needs: [release-alpa]
    steps:
      - uses: actions/checkout@v3

      - name: Bump VERSION and commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b actions/version-bump
          cat VERSION | awk -F. -v OFS=. 'NF==1{print ++$NF}; NF>1{$NF=sprintf("%0*d", length($NF), ($NF+1)); print}' > VERSION.tmp && mv VERSION.tmp VERSION
          git add VERSION
          git commit -m "Bump candidate version [skip ci]"

      - name: Push branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: actions/version-bump
          force: true

      - name: Create version-bump PR
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          source_branch: "actions/version-bump"
          destination_branch: "main"
          pr_title: "Bumping VERSION file due to recent release"
          pr_body: "*Automated PR*: This should update the candidate version. Please delete source branch upon merge"
